/*Copyright (c) 2014, University of Zurich, Department of Informatics, Artificial Intelligence Laboratory
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the copyright holder nor the names of its contributors 
   may be used to endorse or promote products derived from this software without 
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef _ROBOT_PARAM_MAP_
#define _ROBOT_PARAM_MAP_

// Putting all related addresses, subindices, data sizes and data types into pre-defined arrays
// to facilitate subsequent mapping and conversions

#define A01 ACTUAL_POSITION_ADD
#define A02 ACTUAL_VELOCITY_ADD
#define A03 ACTUAL_CURRENT_ADD
#define A04 ANALOG_INPUT_ADD
#define A05 ANALOG_INPUT_ADD
#define A06 ANALOG_INPUT_ADD
#define A07 DEMAND_POSITION_ADD
#define A08 DEMAND_VELOCITY_ADD
#define A09 DEMAND_CURRENT_ADD
#define A10 0	// No corresponding object dictionary entry yet
#define A11 0 // No corresponding object dictionary entry yet
#define A12 0 // No corresponding object dictionary entry yet

#define A13 POSITION_CONTROL_GAINS_ADD
#define A14 POSITION_CONTROL_GAINS_ADD
#define A15 POSITION_CONTROL_GAINS_ADD
#define A16 VELOCITY_CONTROL_GAINS_ADD
#define A17 VELOCITY_CONTROL_GAINS_ADD
#define A18 CURRENT_CONTROL_GAINS_ADD
#define A19 CURRENT_CONTROL_GAINS_ADD
#define A20 0	// No corresponding object dictionary entry yet
#define A21 0	// No corresponding object dictionary entry yet
#define A22 0	// No corresponding object dictionary entry yet

#define A23 OPERATION_MODE_ADD
#define A24 CONTROL_WORD_ADD
#define A25 BUFFER_CONFIG_ADD
#define A26 BUFFER_CONFIG_ADD
#define A27 BUFFER_CONFIG_ADD
#define A28 HEARTBEAT_INTERVAL_ADD
#define A29 MAX_PROFILE_VELOCITY_ADD
#define A30 MAX_ACCELERATION_ADD

#define A31 PDO1_TX_MAPPING_ADD
#define A32 PDO1_TX_MAPPING_ADD
#define A33 PDO1_TX_MAPPING_ADD
#define A34 PDO1_TX_MAPPING_ADD
#define A35 PDO1_TX_PARAMETER_ADD
#define A36 PDO1_TX_PARAMETER_ADD
#define A37 PDO1_TX_PARAMETER_ADD

#define A38 PDO2_TX_MAPPING_ADD
#define A39 PDO2_TX_MAPPING_ADD
#define A40 PDO2_TX_MAPPING_ADD
#define A41 PDO2_TX_MAPPING_ADD
#define A42 PDO2_TX_PARAMETER_ADD
#define A43 PDO2_TX_PARAMETER_ADD
#define A44 PDO2_TX_PARAMETER_ADD

#define A45 PDO3_TX_MAPPING_ADD
#define A46 PDO3_TX_MAPPING_ADD
#define A47 PDO3_TX_MAPPING_ADD
#define A48 PDO3_TX_MAPPING_ADD
#define A49 PDO3_TX_PARAMETER_ADD
#define A50 PDO3_TX_PARAMETER_ADD
#define A51 PDO3_TX_PARAMETER_ADD

#define A52 PDO4_TX_MAPPING_ADD
#define A53 PDO4_TX_MAPPING_ADD
#define A54 PDO4_TX_MAPPING_ADD
#define A55 PDO4_TX_MAPPING_ADD
#define A56 PDO4_TX_PARAMETER_ADD
#define A57 PDO4_TX_PARAMETER_ADD
#define A58 PDO4_TX_PARAMETER_ADD

#define A59 PDO1_RX_MAPPING_ADD
#define A60 PDO1_RX_MAPPING_ADD
#define A61 PDO1_RX_MAPPING_ADD
#define A62 PDO1_RX_MAPPING_ADD
#define A63 PDO1_RX_PARAMETER_ADD
#define A64 PDO1_RX_PARAMETER_ADD

#define A65 PDO2_RX_MAPPING_ADD
#define A66 PDO2_RX_MAPPING_ADD
#define A67 PDO2_RX_MAPPING_ADD
#define A68 PDO2_RX_MAPPING_ADD
#define A69 PDO2_RX_PARAMETER_ADD
#define A70 PDO2_RX_PARAMETER_ADD

#define A71 PDO3_RX_MAPPING_ADD
#define A72 PDO3_RX_MAPPING_ADD
#define A73 PDO3_RX_MAPPING_ADD
#define A74 PDO3_RX_MAPPING_ADD
#define A75 PDO3_RX_PARAMETER_ADD
#define A76 PDO3_RX_PARAMETER_ADD

#define A77 PDO4_RX_MAPPING_ADD
#define A78 PDO4_RX_MAPPING_ADD
#define A79 PDO4_RX_MAPPING_ADD
#define A80 PDO4_RX_MAPPING_ADD
#define A81 PDO4_RX_PARAMETER_ADD
#define A82 PDO4_RX_PARAMETER_ADD

#define A83 HOME_METHOD_ADD
#define A84 HOME_POSITION_ADD
#define A85 INTERPOLATION_MODE_STATUS_ADD

#define A86 DIGITAL_INPUT_CONFIGURATION_ADD
#define A87 DIGITAL_INPUT_CONFIGURATION_ADD
#define A88 DIGITAL_INPUT_CONFIGURATION_ADD
#define A89 DIGITAL_INPUT_CONFIGURATION_ADD
#define A90 DIGITAL_INPUT_CONFIGURATION_ADD
#define A91 DIGITAL_INPUT_CONFIGURATION_ADD
#define A92 DIGITAL_INPUT_FUNCTIONALITIES_ADD
#define A93 DIGITAL_INPUT_FUNCTIONALITIES_ADD
#define A94 DIGITAL_INPUT_FUNCTIONALITIES_ADD
#define A95 DIGITAL_INPUT_FUNCTIONALITIES_ADD

#define A96 DIGITAL_OUTPUT_CONFIGURATION_ADD
#define A97 DIGITAL_OUTPUT_CONFIGURATION_ADD
#define A98 DIGITAL_OUTPUT_FUNCTIONALITIES_ADD
#define A99 DIGITAL_OUTPUT_FUNCTIONALITIES_ADD
#define A100 DIGITAL_OUTPUT_FUNCTIONALITIES_ADD

// SubIndices
#define S01 ACTUAL_POSITION_SUBINDEX
#define S02 ACTUAL_VELOCITY_SUBINDEX
#define S03 ACTUAL_CURRENT_SUBINDEX
#define S04 ANALOG_INPUT_1_SUBINDEX
#define S05 ANALOG_INPUT_1_SUBINDEX
#define S06 ANALOG_INPUT_2_SUBINDEX
#define S07 DEMAND_POSITION_SUBINDEX
#define S08 DEMAND_VELOCITY_SUBINDEX
#define S09 DEMAND_CURRENT_SUBINDEX
#define S10 0	// No corresponding object dictionary entry yet
#define S11 0 // No corresponding object dictionary entry yet
#define S12 0 // No corresponding object dictionary entry yet

#define S13 POSITION_CONTROL_P_GAIN_SUBINDEX
#define S14 POSITION_CONTROL_I_GAIN_SUBINDEX
#define S15 POSITION_CONTROL_D_GAIN_SUBINDEX
#define S16 VELOCITY_CONTROL_P_GAIN_SUBINDEX
#define S17 VELOCITY_CONTROL_I_GAIN_SUBINDEX
#define S18 CURRENT_CONTROL_P_GAIN_SUBINDEX
#define S19 CURRENT_CONTROL_I_GAIN_SUBINDEX
#define S20 0	// No corresponding object dictionary entry yet
#define S21 0	// No corresponding object dictionary entry yet
#define S22 0	// No corresponding object dictionary entry yet

#define S23 OPERATION_MODE_SUBINDEX
#define S24 CONTROL_WORD_SUBINDEX
#define S25 BUFFER_CLEAR_ENABLE_SUBINDEX
#define S26 BUFFER_CURRENT_SIZE_SUBINDEX
#define S27 BUFFER_REMAINING_MEMORY_SUBINDEX
#define S28 HEARTBEAT_INTERVAL_SUBINDEX
#define S29 MAX_PROFILE_VELOCITY_SUBINDEX
#define S30 MAX_ACCELERATION_SUBINDEX

#define S31 PDO_MAPPING_SIZE_SUBINDEX
#define S32 PDO_MAPPING_ENTRY1_SUBINDEX
#define S33 PDO_MAPPING_ENTRY2_SUBINDEX
#define S34 PDO_MAPPING_ENTRY3_SUBINDEX
#define S35 PDO_PARAMTER_COBID_SUBINDEX
#define S36 PDO_PARAMTER_TYPE_SUBINDEX
#define S37 PDO_PARAMTER_INHIBIT_SUBINDEX

#define S38 PDO_MAPPING_SIZE_SUBINDEX
#define S39 PDO_MAPPING_ENTRY1_SUBINDEX
#define S40 PDO_MAPPING_ENTRY2_SUBINDEX
#define S41 PDO_MAPPING_ENTRY3_SUBINDEX
#define S42 PDO_PARAMTER_COBID_SUBINDEX
#define S43 PDO_PARAMTER_TYPE_SUBINDEX
#define S44 PDO_PARAMTER_INHIBIT_SUBINDEX

#define S45 PDO_MAPPING_SIZE_SUBINDEX
#define S46 PDO_MAPPING_ENTRY1_SUBINDEX
#define S47 PDO_MAPPING_ENTRY2_SUBINDEX
#define S48 PDO_MAPPING_ENTRY3_SUBINDEX
#define S49 PDO_PARAMTER_COBID_SUBINDEX
#define S50 PDO_PARAMTER_TYPE_SUBINDEX
#define S51 PDO_PARAMTER_INHIBIT_SUBINDEX

#define S52 PDO_MAPPING_SIZE_SUBINDEX
#define S53 PDO_MAPPING_ENTRY1_SUBINDEX
#define S54 PDO_MAPPING_ENTRY2_SUBINDEX
#define S55 PDO_MAPPING_ENTRY3_SUBINDEX
#define S56 PDO_PARAMTER_COBID_SUBINDEX
#define S57 PDO_PARAMTER_TYPE_SUBINDEX
#define S58 PDO_PARAMTER_INHIBIT_SUBINDEX

#define S59 PDO_MAPPING_SIZE_SUBINDEX
#define S60 PDO_MAPPING_ENTRY1_SUBINDEX
#define S61 PDO_MAPPING_ENTRY2_SUBINDEX
#define S62 PDO_MAPPING_ENTRY3_SUBINDEX
#define S63 PDO_PARAMTER_COBID_SUBINDEX
#define S64 PDO_PARAMTER_TYPE_SUBINDEX

#define S65 PDO_MAPPING_SIZE_SUBINDEX
#define S66 PDO_MAPPING_ENTRY1_SUBINDEX
#define S67 PDO_MAPPING_ENTRY2_SUBINDEX
#define S68 PDO_MAPPING_ENTRY3_SUBINDEX
#define S69 PDO_PARAMTER_COBID_SUBINDEX
#define S70 PDO_PARAMTER_TYPE_SUBINDEX

#define S71 PDO_MAPPING_SIZE_SUBINDEX
#define S72 PDO_MAPPING_ENTRY1_SUBINDEX
#define S73 PDO_MAPPING_ENTRY2_SUBINDEX
#define S74 PDO_MAPPING_ENTRY3_SUBINDEX
#define S75 PDO_PARAMTER_COBID_SUBINDEX
#define S76 PDO_PARAMTER_TYPE_SUBINDEX

#define S77 PDO_MAPPING_SIZE_SUBINDEX
#define S78 PDO_MAPPING_ENTRY1_SUBINDEX
#define S79 PDO_MAPPING_ENTRY2_SUBINDEX
#define S80 PDO_MAPPING_ENTRY3_SUBINDEX
#define S81 PDO_PARAMTER_COBID_SUBINDEX
#define S82 PDO_PARAMTER_TYPE_SUBINDEX

#define S83 HOME_METHOD_SUBINDEX
#define S84 HOME_POSITION_SUBINDEX
#define S85 INTERPOLATION_MODE_STATUS_SUBINDEX

#define S86 DIGITAL_INPUT_1_CONFIGURATION_SUBINDEX
#define S87 DIGITAL_INPUT_2_CONFIGURATION_SUBINDEX
#define S88 DIGITAL_INPUT_3_CONFIGURATION_SUBINDEX
#define S89 DIGITAL_INPUT_4_CONFIGURATION_SUBINDEX
#define S90 DIGITAL_INPUT_5_CONFIGURATION_SUBINDEX
#define S91 DIGITAL_INPUT_6_CONFIGURATION_SUBINDEX
#define S92 DIGITAL_INPUT_STATE_SUBINDEX
#define S93 DIGITAL_INPUT_MASK_SUBINDEX
#define S94 DIGITAL_INPUT_POLARITY_SUBINDEX
#define S95 DIGITAL_INPUT_EXECUTION_MASK_SUBINDEX

#define S96 DIGITAL_OUTPUT_1_CONFIGURATION_SUBINDEX
#define S97 DIGITAL_OUTPUT_2_CONFIGURATION_SUBINDEX
#define S98 DIGITAL_OUTPUT_STATE_SUBINDEX
#define S99 DIGITAL_OUTPUT_MASK_SUBINDEX
#define S100 DIGITAL_OUTPUT_POLARITY_SUBINDEX

// Data size
#define D01 0 // Not writable
#define D02 0 // Not writable
#define D03 0 // Not writable
#define D04 0 // Not writable
#define D05 0 // Not writable
#define D06 0 // Not writable
#define D07 DEMAND_POSITION_DATA_SIZE
#define D08 DEMAND_VELOCITY_DATA_SIZE
#define D09 DEMAND_CURRENT_DATA_SIZE
#define D10 0	// No corresponding object dictionary entry yet
#define D11 0 // No corresponding object dictionary entry yet
#define D12 0 // No corresponding object dictionary entry yet

#define D13 CONTROL_GAIN_DATA_SIZE
#define D14 CONTROL_GAIN_DATA_SIZE
#define D15 CONTROL_GAIN_DATA_SIZE
#define D16 CONTROL_GAIN_DATA_SIZE
#define D17 CONTROL_GAIN_DATA_SIZE
#define D18 CONTROL_GAIN_DATA_SIZE
#define D19 CONTROL_GAIN_DATA_SIZE
#define D20 0	// No corresponding object dictionary entry yet
#define D21 0	// No corresponding object dictionary entry yet
#define D22 0	// No corresponding object dictionary entry yet

#define D23 OPERATION_MODE_DATA_SIZE
#define D24 CONTROL_WORD_DATA_SIZE
#define D25 BUFFER_CLEAR_ENABLE_DATA_SIZE
#define D26 BUFFER_REMAINING_MEMORY_DATA_SIZE
#define D27 BUFFER_CURRENT_SIZE_DATA_SIZE
#define D28 HEARTBEAT_INTERVAL_DATA_SIZE
#define D29 MAX_PROFILE_VELOCITY_DATA_SIZE
#define D30 MAX_ACCELERATION_DATA_SIZE

#define D31 PDO_MAPPING_SIZE_DATA_SIZE
#define D32 PDO_MAPPING_ENTRY_DATA_SIZE
#define D33 PDO_MAPPING_ENTRY_DATA_SIZE
#define D34 PDO_MAPPING_ENTRY_DATA_SIZE
#define D35 PDO_PARAMTER_COBID_DATA_SIZE
#define D36 PDO_PARAMTER_TYPE_DATA_SIZE
#define D37 PDO_PARAMTER_INHIBIT_DATA_SIZE

#define D38 PDO_MAPPING_SIZE_DATA_SIZE
#define D39 PDO_MAPPING_ENTRY_DATA_SIZE
#define D40 PDO_MAPPING_ENTRY_DATA_SIZE
#define D41 PDO_MAPPING_ENTRY_DATA_SIZE
#define D42 PDO_PARAMTER_COBID_DATA_SIZE
#define D43 PDO_PARAMTER_TYPE_DATA_SIZE
#define D44 PDO_PARAMTER_INHIBIT_DATA_SIZE

#define D45 PDO_MAPPING_SIZE_DATA_SIZE
#define D46 PDO_MAPPING_ENTRY_DATA_SIZE
#define D47 PDO_MAPPING_ENTRY_DATA_SIZE
#define D48 PDO_MAPPING_ENTRY_DATA_SIZE
#define D49 PDO_PARAMTER_COBID_DATA_SIZE
#define D50 PDO_PARAMTER_TYPE_DATA_SIZE
#define D51 PDO_PARAMTER_INHIBIT_DATA_SIZE

#define D52 PDO_MAPPING_SIZE_DATA_SIZE
#define D53 PDO_MAPPING_ENTRY_DATA_SIZE
#define D54 PDO_MAPPING_ENTRY_DATA_SIZE
#define D55 PDO_MAPPING_ENTRY_DATA_SIZE
#define D56 PDO_PARAMTER_COBID_DATA_SIZE
#define D57 PDO_PARAMTER_TYPE_DATA_SIZE
#define D58 PDO_PARAMTER_INHIBIT_DATA_SIZE

#define D59 PDO_MAPPING_SIZE_DATA_SIZE
#define D60 PDO_MAPPING_ENTRY_DATA_SIZE
#define D61 PDO_MAPPING_ENTRY_DATA_SIZE
#define D62 PDO_MAPPING_ENTRY_DATA_SIZE
#define D63 PDO_PARAMTER_COBID_DATA_SIZE
#define D64 PDO_PARAMTER_TYPE_DATA_SIZE

#define D65 PDO_MAPPING_SIZE_DATA_SIZE
#define D66 PDO_MAPPING_ENTRY_DATA_SIZE
#define D67 PDO_MAPPING_ENTRY_DATA_SIZE
#define D68 PDO_MAPPING_ENTRY_DATA_SIZE
#define D69 PDO_PARAMTER_COBID_DATA_SIZE
#define D70 PDO_PARAMTER_TYPE_DATA_SIZE

#define D71 PDO_MAPPING_SIZE_DATA_SIZE
#define D72 PDO_MAPPING_ENTRY_DATA_SIZE
#define D73 PDO_MAPPING_ENTRY_DATA_SIZE
#define D74 PDO_MAPPING_ENTRY_DATA_SIZE
#define D75 PDO_PARAMTER_COBID_DATA_SIZE
#define D76 PDO_PARAMTER_TYPE_DATA_SIZE

#define D77 PDO_MAPPING_SIZE_DATA_SIZE
#define D78 PDO_MAPPING_ENTRY_DATA_SIZE
#define D79 PDO_MAPPING_ENTRY_DATA_SIZE
#define D80 PDO_MAPPING_ENTRY_DATA_SIZE
#define D81 PDO_PARAMTER_COBID_DATA_SIZE
#define D82 PDO_PARAMTER_TYPE_DATA_SIZE

#define D83 HOME_METHOD_DATA_SIZE
#define D84 HOME_POSITION_DATA_SIZE
#define D85 0 // Not writable

#define D86 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D87 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D88 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D89 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D90 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D91 DIGITAL_INPUT_CONFIGURATION_DATA_SIZE
#define D92 DIGITAL_INPUT_STATE_DATA_SIZE
#define D93 DIGITAL_INPUT_MASK_DATA_SIZE
#define D94 DIGITAL_INPUT_POLARITY_DATA_SIZE
#define D95 DIGITAL_INPUT_EXECUTION_MASK_DATA_SIZE

#define D96 DIGITAL_OUTPUT_CONFIGURATION_DATA_SIZE
#define D97 DIGITAL_OUTPUT_CONFIGURATION_DATA_SIZE
#define D98 DIGITAL_OUTPUT_STATE_DATA_SIZE
#define D99 DIGITAL_OUTPUT_MASK_DATA_SIZE
#define D100 DIGITAL_OUTPUT_POLARITY_DATA_SIZE

#endif
