
FIND_PATH(
	EST_INCLUDE_DIR
  EST.h
	/usr/include/estools/
)

FIND_LIBRARY(
  ESTOOLS_LIBRARY
  NAMES estools
  PATHS
  /usr/lib
)

FIND_LIBRARY(
  ESTBASE_LIBRARY
  NAMES estbase
  PATHS
  /usr/lib
)

FIND_LIBRARY(
  ESTSTRING_LIBRARY
  NAMES eststring
  PATHS
  /usr/lib
)


MESSAGE (STATUS "EST INCLUDE DIR  " ${EST_INCLUDE_DIR})
MESSAGE (STATUS "ESTOOLS LIBRARY  " ${ESTOOLS_LIBRARY})
MESSAGE (STATUS "ESTBASE LIBRARY  " ${ESTBASE_LIBRARY})
MESSAGE (STATUS "ESTSTRING LIBRARY  " ${ESTSTRING_LIBRARY})



IF (EST_INCLUDE_DIR AND ESTOOLS_LIBRARY AND ESTBASE_LIBRARY AND ESTSTRING_LIBRARY)
    SET(EST_FOUND TRUE)
    SET(EST_LIBRARIES  ${ESTOOLS_LIBRARY} ${ESTBASE_LIBRARY} ${ESTSTRING_LIBRARY}) 
    MESSAGE (STATUS "EST project found " ${FESTIVAL_LIBRARIES})
ELSE ( FESTIVAL_INCLUDE_DIR AND EST_INCLUDE_DIR AND FESTIVAL_LIBRARY AND ESTOOLS_LIBRARY AND ESTBASE_LIBRARY AND ESTSTRING_LIBRARY )
    SET(EST_FOUND FALSE)
    IF(EST_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "EST project was not found!")
    ELSE (EST_FIND_REQUIRED)
        IF(NOT EST_FIND_QUIETLY)
            MESSAGE( STATUS "EST project was not found!")
        ENDIF(NOT EST_FIND_QUIETLY)
    ENDIF(EST_FIND_REQUIRED)
ENDIF ( EST_INCLUDE_DIR AND ESTOOLS_LIBRARY AND ESTBASE_LIBRARY AND ESTSTRING_LIBRARY )

MARK_AS_ADVANCED(
	EST_FOUND
  EST_INCLUDE_DIR
	EST_LIBRARY
	EST_LIBRARIES
) 
