
FIND_PATH(
	ROBOY_UTILS_INCLUDE_DIR
	roboy/RoboyTransforms.h
    ${CMAKE_SOURCE_DIR}/src/roboy/utils
)

FIND_LIBRARY(
  ROBOY_UTILS_LIBRARY
  NAMES RoboyUtilsd
  PATHS
  ${CMAKE_SOURCE_DIR}/src/roboy/utils
)
    
MESSAGE (STATUS "HUGO  " ${ROBOY_UTILS_LIBRARY})
MESSAGE (STATUS "HUGO2  " ${ROBOY_UTILS_INCLUDE_DIR})

IF (	ROBOY_UTILS_INCLUDE_DIR AND ROBOY_UTILS_LIBRARY )
    SET(ROBOY_UTILS_FOUND TRUE)
    SET(ROBOY_UTILS_LIBRARIES ${ROBOY_UTILS_LIBRARY}) 
    MESSAGE (STATUS "RoboyUtils project found")
ELSE ( ROBOY_UTILS_INCLUDE_DIR AND ROBOY_UTILS_LIBRARY )
    SET(ROBOY_UTILS_FOUND FALSE)
    IF(ROBOY_UTILS_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "RoboyUtils project was not found!")
    ELSE (ROBOY_UTILS_FIND_REQUIRED)
        IF(NOT ROBOY_UTILS_FIND_QUIETLY)
            MESSAGE( STATUS "RoboyUtils project was not found!")
        ENDIF(NOT ROBOY_UTILS_FIND_QUIETLY)
    ENDIF(ROBOY_UTILS_FIND_REQUIRED)
ENDIF ( ROBOY_UTILS_INCLUDE_DIR AND ROBOY_UTILS_LIBRARY )

MARK_AS_ADVANCED(
	ROBOY_UTILS_FOUND
	ROBOY_UTILS_INCLUDE_DIR
	ROBOY_UTILS_LIBRARY
	ROBOY_UTILS_LIBRARIES
) 
