
FIND_PATH(
	PCAN_USB_INCLUDE_DIR
  libpcan.h
	/usr/include
)

FIND_LIBRARY(
  PCAN_USB_LIBRARY
  NAMES pcan
  PATHS
  /usr/lib
)
    

MESSAGE (STATUS "PCAN INCLUDE DIR " ${PCAN_USB_INCLUDE_DIR})
MESSAGE (STATUS "PCAN LIBRARY DIR " ${PCAN_USB_LIBRARY})


IF (PCAN_USB_INCLUDE_DIR AND PCAN_USB_LIBRARY )
    SET(PCAN_USB_FOUND TRUE)
    MESSAGE (STATUS "PCAN_USB project found " ${PCAN_USB_LIBRARY})
ELSE ( PCAN_USB_INCLUDE_DIR AND PCAN_USB_LIBRARY )
    SET(PCAN_USB_FOUND FALSE)
    IF(PCAN_USB_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "PCAN_USB project was not found!")
    ELSE (PCAN_USB_FIND_REQUIRED)
        IF(NOT PCAN_USB_FIND_QUIETLY)
            MESSAGE( STATUS "PCAN_USB project was not found!")
        ENDIF(NOT PCAN_USB_FIND_QUIETLY)
    ENDIF(PCAN_USB_FIND_REQUIRED)
ENDIF ( PCAN_USB_INCLUDE_DIR AND PCAN_USB_LIBRARY )

MARK_AS_ADVANCED(
	PCAN_USB_FOUND
	PCAN_USB_INCLUDE_DIR
	PCAN_USB_LIBRARY
) 
