
FIND_PATH(
	FESTIVAL_INCLUDE_DIR
  festival.h
	/usr/include
  /usr/include/festival
)

FIND_LIBRARY(
  FESTIVAL_LIBRARY
  NAMES Festival
  PATHS
  /usr/lib
)
    

MESSAGE (STATUS "FESTIVAL INCLUDE DIR  " ${FESTIVAL_INCLUDE_DIR})
MESSAGE (STATUS "FESTIVAL LIBRARY  " ${FESTIVAL_LIBRARY})


IF (FESTIVAL_INCLUDE_DIR AND FESTIVAL_LIBRARY )
    SET(FESTIVAL_FOUND TRUE)
    MESSAGE (STATUS "Festival project found " ${FESTIVAL_LIBRARIES})
ELSE ( FESTIVAL_INCLUDE_DIR AND FESTIVAL_LIBRARY )
    SET(FESTIVAL_FOUND FALSE)
    IF(FESTIVAL_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "Festival project was not found!")
    ELSE (FESTIVAL_FIND_REQUIRED)
        IF(NOT FESTIVAL_FIND_QUIETLY)
            MESSAGE( STATUS "Festival project was not found!")
        ENDIF(NOT FESTIVAL_FIND_QUIETLY)
    ENDIF(FESTIVAL_FIND_REQUIRED)
ENDIF ( FESTIVAL_INCLUDE_DIR AND FESTIVAL_LIBRARY )

MARK_AS_ADVANCED(
	FESTIVAL_FOUND
	FESTIVAL_INCLUDE_DIR
	FESTIVAL_LIBRARY
) 
