IF(${CMAKE_SIZEOF_VOID_P} EQUAL 8)
    MESSAGE(STATUS "Found 64bit architecture.")
    SET(MVBLUEFOX_DIR mvIMPACTx86-64)
ELSEIF(${CMAKE_SIZEOF_VOID_P} EQUAL 4)
    MESSAGE(STATUS "Found 32bit architecture.")
    SET(MVBLUEFOX_DIR mvIMPACT_acquire-x86)
ELSE()
    MESSAGE(FATAL_ERROR "Could not detect host architecture.")
ENDIF()


FIND_PATH(
	MVBLUEFOX_INCLUDE_DIR
  mvIMPACT_CPP/mvIMPACT_acquire.h
  ${CMAKE_SOURCE_DIR}/../libs/${MVBLUEFOX_DIR}
)

FIND_LIBRARY(
  MVBLUEFOX_LIBRARY
  NAMES mvBlueFOX
  PATHS
  ${CMAKE_SOURCE_DIR}/../libs/${MVBLUEFOX_DIR}/lib/
)
    

FIND_LIBRARY(
  MVBLUEFOXDEVICE_LIBRARY
  NAMES mvDeviceManager
  PATHS
  ${CMAKE_SOURCE_DIR}/../libs/${MVBLUEFOX_DIR}/lib/
)

FIND_LIBRARY(
  MVBLUEFOXPROP_LIBRARY
  NAMES mvPropHandling
  PATHS
  ${CMAKE_SOURCE_DIR}/../libs/${MVBLUEFOX_DIR}/lib/
)


MESSAGE (STATUS "MVBLUEFOX INCLUDE DIR " ${MVBLUEFOX_INCLUDE_DIR})
MESSAGE (STATUS "MVBLUEFOX LIBRARY " ${MVBLUEFOX_LIBRARY})

IF (MVBLUEFOX_INCLUDE_DIR AND MVBLUEFOX_LIBRARY )
    SET(MVBLUEFOX_FOUND TRUE)
    SET(MVBLUEFOX_LIBRARIES  ${MVBLUEFOX_LIBRARY} ${MVBLUEFOXDEVICE_LIBRARY} ${MVBLUEFOXPROP_LIBRARY})
    MESSAGE (STATUS "MVBLUEFOX project found " ${MVBLUEFOX_LIBRARIES})
ELSE ( MVBLUEFOX_INCLUDE_DIR AND MVBLUEFOX_LIBRARY )
    SET(MVBLUEFOX_FOUND FALSE)
    IF(MVBLUEFOX_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "MVBLUEFOX project was not found!")
    ELSE (MVBLUEFOX_FIND_REQUIRED)
        IF(NOT MVBLUEFOX_FIND_QUIETLY)
            MESSAGE( STATUS "MVBLUEFOX project was not found!")
        ENDIF(NOT MVBLUEFOX_FIND_QUIETLY)
    ENDIF(MVBLUEFOX_FIND_REQUIRED)
ENDIF ( MVBLUEFOX_INCLUDE_DIR AND MVBLUEFOX_LIBRARY )

MARK_AS_ADVANCED(
	MVBLUEFOX_FOUND
	MVBLUEFOX_INCLUDE_DIR
	MVBLUEFOX_LIBRARY
  MVBLUEFOX_LIBRARIES
) 
