
FIND_PATH(
	ALUT_INCLUDE_DIR
  alut.h
	/usr/include/AL
)

FIND_LIBRARY(
  ALUT_LIBRARY
  NAMES alut
  PATHS
  /usr/lib
)
    

MESSAGE (STATUS "ALUT INCLUDE DIR " ${ALUT_INCLUDE_DIR})
MESSAGE (STATUS "ALUT LIBRARY " ${ALUT_LIBRARY})


IF (ALUT_INCLUDE_DIR AND ALUT_LIBRARY )
    SET(ALUT_FOUND TRUE)
    MESSAGE (STATUS "ALUT project found " ${ALUT_LIBRARIES})
ELSE ( ALUT_INCLUDE_DIR AND ALUT_LIBRARY )
    SET(ALUT_FOUND FALSE)
    IF(ALUT_FIND_REQUIRED)
        MESSAGE( FATAL_ERROR "ALUT project was not found!")
    ELSE (ALUT_FIND_REQUIRED)
        IF(NOT ALUT_FIND_QUIETLY)
            MESSAGE( STATUS "ALUT project was not found!")
        ENDIF(NOT ALUT_FIND_QUIETLY)
    ENDIF(ALUT_FIND_REQUIRED)
ENDIF ( ALUT_INCLUDE_DIR AND ALUT_LIBRARY )

MARK_AS_ADVANCED(
	ALUT_FOUND
	ALUT_INCLUDE_DIR
	ALUT_LIBRARY
) 
